name = "dealer"
version = "0.7.9"
default_install_root = "~/zyng/apps/dealer/"
setup_venv = true
entrypoint = "src/app/main.py"
icon = "data/icons/d4.png"

[source]
type = "git"
location = "https://github.com/WOLFBED/d4"
sha256 = ""
gpg_key = ""
gpg_signature = ""

[required_apps]
apps = ["deno"]
